server:
  port: 4100

spring:
  application:
    name: xuanyu-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jadyer/demo-cloud/ # 配置Git仓库的地址
          searchPaths: config-repo                  # Git仓库下的相对地址（支持多个，用半角逗号分隔）
          # username: username                       # 只有private的项目才需要配置用户名和密码
          # password: password                       # 只有private的项目才需要配置用户名和密码

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:1100/eureka/